### ISSUE TITLE
Support for Voicemeeter Potato

### ISSUE THREAD

**Issue by djmattyg007** [ChewbaccaCookie/voicemeeter-connector#13]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Voicemeeter Potato supports up to five hardware inputs (A1-5) and three virtual inputs (B1-3). Unfortunately this package only has constants for A1-3 and B1-2. It would be great if constants could be added for the additional inputs.

**Comment by ChewbaccaCookie** [comment]
Thanks for your feature request, I will have a look at this.

**Comment by ChewbaccaCookie** [comment]
Closed with release v1.1 (NPM: 0.6.1)

**Comment by djmattyg007** [comment]
Thank you so much!
