### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by jehendeoff** [ChewbaccaCookie/voicemeeter-connector#15]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ x] question about how to use this project

* **Summary**
Hi I'm having an issue with the command `npm install --global --production windows-build-tools@4.0.0 --vs2015` it is taking forever and it blocked at "
------------------- Python --------------------
Still waiting for installer log file...    "

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I do have python 2.7.6 and I think it might be the issue here

**Comment by ChewbaccaCookie** [comment]
Hey, could you please try to install the tools with the following command 
`npm install --global --production windows-build-tools`

Moreover make sure that you use Node 8 or 10.
