### ISSUE TITLE
[Feature]: Implement special commands

### ISSUE THREAD

**Issue by blushell** [ChewbaccaCookie/voicemeeter-connector#19]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Ability To use special command like "Command.Restart or Command.Show"
also could you please add the record commands. Thank you! amazing job so far!!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ChewbaccaCookie** [comment]
Hey, 
I will look whether it's possible by the API.

**Comment by elydan** [comment]
Hello :)

Do you have any news on this? I will be really happy when I can use the recorder with your tool: D

Thank you for your reply !

**Comment by ChewbaccaCookie** [comment]
Ohh sorry,
Ohh excuse me,
currently I have no time to implement this. Feel free to make a Pull Request. 

Many greetings
