### ISSUE TITLE
Segmentation fault while disconnecting

### ISSUE THREAD

**Issue by K4M1s** [ChewbaccaCookie/voicemeeter-connector#23]
* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Node is crashing with `Segmentation fault` error while using vm.disconnect();
```javascript
VoiceMeeter.default.init().then(vm => {
	// Connect to your Voicemeeter client
	vm.connect();

	vm.attachChangeEvent(()=> {
        console.log("Something changed!")
    })

	//Disconnect voicemeeter client
	setTimeout(vm.disconnect, 500);
});
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Node version: v10.23.3

**Comment by ChewbaccaCookie** [comment]
Hi, sorry for respondig so late.
Which Version of Voidemeeter did you use?

**Comment by K4M1s** [comment]
Banana, Version: 2.0.5.4

**Comment by ChewbaccaCookie** [comment]
Okay, I will have a look at this

**Comment by ChewbaccaCookie** [comment]
Hi, i updated the package to version v1.0.2 with node support v10 - v15. Please update to this version and try again. If you encounter the same issue again try to add `process.exit(0);` after disconnecting:

```javascript
// Disconnect voicemeeter client
setTimeout(() => {
  vm.disconnect();
  process.exit(0);
}, 5000);
```


**Be aware that the default import has been changed in new version:**
*Before:*
```javascript
import Voicemeeter, {StripProperties } from "voicemeeter-connector";
```
*Now:*
```javascript
import { Voicemeeter, StripProperties } from "voicemeeter-connector";
```

**Comment by ChewbaccaCookie** [comment]
I will close this issue due to inactivity
