### ISSUE TITLE
Unable to get strip label

### ISSUE THREAD

**Issue by terenc3** [ChewbaccaCookie/voicemeeter-connector#25]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I'm unable to get the strip label `vm.getStripParameter(0, 'Label')` returns 0. I can set the label, but not the other way around.

* **Other information**
VoiceMeeter Banana 2.0.5.3
voicemeeter-connector 1.0.2
node 10.24.1
npm 6.14.12
windows 10 home 19041.1052

**Comment by ChewbaccaCookie** [comment]
Hi,
I'm sorry, I currently have no time to work actively on this repo. 
If you find a solution, feel free to open a pull request or comment a solution at this issue.

Kind regards

**Comment by terenc3** [comment]
I think the problem lies here

https://github.com/ChewbaccaCookie/voicemeeter-connector/blob/58713066fc46bce7dd2507a8924a647788001747/src/lib/VoicemeeterConnector.ts#L287

VBVMR_GetParameterFloat is used but i think for label (an other) VBVMR_GetParameterStringA is needed.

I've tried this solution which works, but crashes my applicaiton afterwards with "Process finished with exit code -1073740940 (0xC0000374)" I've probably did something wrong with libVM library

```js
if (["Label", "FadeTo", "FadeBy", "AppGain", "AppMute", "device.name"].indexOf(property) > -1) {
	const namePtr = new CharArray(256);
	libVM.VBVMR_GetParameterStringA(hardwareIdPtr, namePtr);
	return String.fromCharCode.apply(null, namePtr);
}
```

```js
console.log('a', vm.getStripParameter(0, 'Label'))
console.log('b', vm.getStripParameter(0, 'device.name'))
```
which prints
```js
a Microphone
b Mikrofon (4- AUNA MIC-920)
```

**Comment by edo2313** [comment]
@terenc3 Thanks for pointing it out, I worked on your fix so now it works correctly and doesn't crash anymore.
@ChewbaccaCookie For reference, PR #26
