### ISSUE TITLE
HTTP calls / requests

### ISSUE THREAD

**Issue by mach7** [ChewbaccaCookie/voicemeeter-connector#30]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X ] question about how to use this project

* **Summary**
Is it possible to pass HTTP calls to this and have it interface with Voicemeeter? Looking to do what this project was suppose to do: https://github.com/Mikatux/voicemeeter-api 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ChewbaccaCookie** [comment]
Hi, I would close the issue due to inactivity. Please reopen it, in case you have any more questions.
